{ ... }: {
  # Share the user's OrcaSlicer print presets between hosts.
  #
  # Only the three preset subtrees are involved — `machine`, `process` and
  # `filament` under `user/default/`. Everything else in the application's data
  # directory is deliberately out of scope: `.orcaslicer_machine_id` is a
  # per-machine UUID, `OrcaSlicer.conf` carries window geometry and recent-file
  # state, `system/` is regenerated by the application from its bundled profiles
  # on every version change, and `printers/`, `cache/`, `log/`, `ota/` and
  # `user_backup-*` are application-managed or transient.
  #
  # The seed never overwrites, so it is safe on a host that already has presets
  # and safe to re-run on every activation. Repo-side edits reach a host that
  # already has the files through `scripts/slicer-presets.sh orca pull`;
  # capturing GUI edits back into the repository is
  # `scripts/slicer-presets.sh orca push`.
  #
  # The presets reference system preset names through their `inherits` chains, so
  # both hosts should stay on the same `nixpkgs-orca` pin; the flake gives that
  # for free.
  flake.homeModules.orcaslicer-presets = { config, lib, ... }: {
    home.activation.orcaPresetSeed = lib.hm.dag.entryAfter [ "writeBoundary" ] (
      import ../lib/_preset-seed.nix {
        src = ../../dotfiles/orcaslicer/user-default;
        dst = "${config.home.homeDirectory}/.config/OrcaSlicer/user/default";
      }
    );
  };
}
