#!/usr/bin/env bash
#
# seed-gentle-profiles.sh — install the gentle-profile model-routing profiles
# on a host that does not have them yet (gear5th), without needing any network
# or SSH between the machines.
#
# gentle-profile (the routing switcher gentle-ai installs) reads its profiles
# from ~/.pi/gentle-ai/profiles/<name>.json and generates profiles.json,
# models.json and subagents.json from them. Those generated files are runtime
# state the tool rewrites, so they are deliberately NOT managed declaratively;
# this script only seeds the authored profiles from the copies vendored in
# dotfiles/pi-gentle-ai/, and it copies (never symlinks) so the tool can keep
# editing them.
#
# Usage:
#   ./scripts/seed-gentle-profiles.sh          # seed (backs up differences)
#   ./scripts/seed-gentle-profiles.sh --check  # report only, change nothing

set -euo pipefail

CHECK_ONLY=0
for arg in "$@"; do
    case "$arg" in
        --check) CHECK_ONLY=1 ;;
        -h|--help) awk 'NR>1 && /^set -euo/{exit} NR>1 {sub(/^# ?/, ""); print}' "$0"; exit 0 ;;
        *) echo "[x] unknown argument: $arg" >&2; exit 2 ;;
    esac
done

REPO_DIR="${REPO_DIR:-$(cd "$(dirname "$0")/.." && pwd)}"
SRC="$REPO_DIR/dotfiles/pi-gentle-ai"
DEST="${GENTLE_PI_CONFIG_HOME:-$HOME/.pi/gentle-ai}"

ok() { printf '[+] %s\n' "$*"; }
warn() { printf '[!] %s\n' "$*"; }

if [ ! -d "$SRC" ]; then
    echo "[x] no vendored profiles at $SRC (run from the repo, or set REPO_DIR)" >&2
    exit 1
fi

seed() { # seed <source> <destination>
    local src="$1" dst="$2"
    if [ -f "$dst" ] && cmp -s "$src" "$dst"; then
        ok "already up to date: $dst"
        return 0
    fi
    if [ "$CHECK_ONLY" -eq 1 ]; then
        if [ -f "$dst" ]; then warn "differs: $dst"; else warn "missing: $dst"; fi
        return 0
    fi
    mkdir -p "$(dirname "$dst")"
    if [ -f "$dst" ]; then
        cp -n "$dst" "$dst.bak.$(date +%Y%m%d%H%M%S)"
        warn "backed up the previous copy of $dst"
    fi
    install -m 0644 "$src" "$dst"
    ok "installed: $dst"
}

seed "$SRC/profiles/base.json" "$DEST/profiles/base.json"
seed "$SRC/profiles/bonus.json" "$DEST/profiles/bonus.json"

# persona.json holds the active persona mode; the tool updates it when the mode
# changes, so only seed it when it does not exist yet.
if [ -f "$DEST/persona.json" ]; then
    ok "persona.json present; left untouched"
elif [ "$CHECK_ONLY" -eq 1 ]; then
    warn "missing: $DEST/persona.json"
else
    mkdir -p "$DEST"
    install -m 0644 "$SRC/persona.json" "$DEST/persona.json"
    ok "installed: $DEST/persona.json"
fi

cat <<'EOF'

[+] Next steps (needs perl and pi on PATH; the probe needs the provider keys):
      gentle-profile list       # available profiles
      gentle-profile current    # active profile
      gentle-profile auto       # probe quota, then apply the right profile

    profiles.json, models.json and subagents.json are regenerated by the tool
    from these profiles; do not manage them declaratively.
EOF
